### PR TITLE
Add session tab context

### PR DESCRIPTION
**Pull request by harshithpabbati**
This PR adds session tabs context

@acao please review this PR

### CODE REVIEW

**Comment by acao** [comment]
@harshithpabbati nice! you read my mind

please follow the instructions in the github action failure and run `yarn format`

**Comment by harshithpabbati** [comment]
Hahaha

**Comment by harshithpabbati** [comment]
Haha

**Comment by harshithpabbati** [comment]
@acao updated the PR

**Comment by harshithpabbati** [comment]
Created a new [PR](https://github.com/graphql/graphiql/pull/1524) in GraphiQL Repo. So, closing this.

**Pull request closed without merging**
