### PR TITLE
feat: first pass graphiql redesign using new layout component

### PR DESCRIPTION
**Pull request by cshaver**
This is a quick first pass at starting to use the new Layout component added in https://github.com/graphql/graphiql/pull/1145 🎉 

Screen Shot 2020-05-05 at 10 38 43 p m

### CODE REVIEW

**Comment by acao** [comment]
@walaura big mood

**Comment by harshithpabbati** [comment]
@acao I added tabs to editors and here is the draft [PR](https://github.com/cshaver/graphiql/pull/1)

Screenshot 2020-05-06 at 9 31 22 PM

But still, I have a small problem. Editor in Query tab is having default height of 5px. I am not able to figure out why it is happening.

**Comment by harshithpabbati** [comment]
> @acao I added tabs to editors and here is the draft [PR](https://github.com/cshaver/graphiql/pull/1)
> 
> Screenshot 2020-05-06 at 9 31 22 PM
> 
> But still, I have a small problem. Editor in Query tab is having default height of 5px. I am not able to figure out why it is happening.

Or should I send a new PR over here?

**Comment by acao** [comment]
@harshithpabbati I think I will merge this PR as is, and you can open your PR against the updated feat/use-context-hooks, sound good?

**Comment by harshithpabbati** [comment]
yeah okay, cool!

**Comment by acao** [comment]
@harshithpabbati now, if you open a PR against `acao:feat/use-context-hooks` like she did, you'll be good to go!

**Comment by harshithpabbati** [comment]
> @harshithpabbati now, if you open a PR against `acao:feat/use-context-hooks` like she did, you'll be good to go!

Yeah, doing it just a min

**Pull request merged**
